version: "3.9"

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm-server
    env_file: .env
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - HF_HOME=/models
      - HUGGING_FACE_HUB_TOKEN=${API_KEY}
    volumes:
      - type: bind
        source: ./models
        target: /models
    command: >
      --model ${MODEL}
      --max-model-len 3000
      --download-dir /models
      --gpu-memory-utilization 0.95
      --quantization awq
volumes:
  models:
